version: '3'

services:
  frontend:
    volumes:
      - "/Users/malmaud/tmp/project/node/src:/project/src"
      - "/Users/malmaud/tmp/project/node/run_devserver.sh:/project/run_devserver.sh"
    command: /bin/bash /project/run_devserver.sh
  backend_julia5:
    volumes:
      - "/Users/malmaud/tmp/project/julia/script.jl:/script.jl"
  db:
    ports:
      - "10002:8080"
    volumes:
      - "/Users/malmaud/tmp/data:/data"
