version: '3'

services:
  backend_julia5:
    build:
      context: ./julia
      dockerfile: Dockerfile.julia5
    ports:
      - "10000:10000"
    restart: unless-stopped
  backend_julia6:
    build:
      context: ./julia
      dockerfile: Dockerfile.julia6
    ports:
      - "10002:10000"
    restart: unless-stopped
  frontend:
    build: node/
    ports:
      - "10001:3000"
    depends_on:
      - db
      - backend_julia5
      - backend_julia6
  db:
    image: rethinkdb
